name: Watch BB Public Program
on:
  workflow_dispatch:
#  schedule:
#  - cron: "0 * * * *"
jobs:
  bbp-watcher:
    runs-on: ubuntu-latest
    env:
       S_TOKEN: ${{ secrets.SLACK_OAUTH_USER_TOKEN }}
       S_CHANNEL: ${{ secrets.SLACK_CHANNEL_NAME }}
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       S_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
       S_URL: https://slack.com/api/files.upload
                 
    steps:
      - uses: actions/checkout@v2
                            
      - name: Get Latest Data
        run: |
         wget --quiet https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/master/data/domains.txt
         wget --quiet https://raw.githubusercontent.com/arkadiyt/bounty-targets-data/master/data/wildcards.txt
      # watcher.py produces two files- domains-new.txt, wildcards-new.txt
      - name: Check for New domains
        run: python3 watcher.py        
      - name: Rename file
        run: |
         cp domains.txt domains-local.txt && cp wildcards.txt wildcards-local.txt
         cat domains-new.txt wildcards-new.txt | tee domains.txt
      - name: Send Files to Slack Channel
        run: |
         today=$(date +"%d_%m_%Y")
         if [[ -f domains.txt ]]; then curl "$S_URL" -F token="$S_TOKEN" -F channels="$S_CHANNEL" -F title="Watch-BBP-Public-Domains-$today" -F file=@domains.txt; fi
      - name: Commit Output files
        run: |
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git add domains-local.txt wildcards-local.txt
         git commit -m "Update Local Files"
         git push "https://ValluvarSploit:${{ secrets.TOKEN }}@github.com/ValluvarSploit/Watch-BBP-Public.git" HEAD:main --follow-tags
      - name: Job Stauts Slack Notification
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The job ${{ github.job}} in workflow ${{ github.workflow }} has _*`${{ job.status }}`*_"}' "$S_WEBHOOK"
